export const TYPES = {
  CHANGE_NAME: "CHANGE_NAME",
  CLEAR_PURCHASES: "CLEAR_PURCHASES",

  ADD_PURCHASES: "ADD_PURCHASES",

  SHOW_LIMIT_MODAL: "SHOW_LIMIT_MODAL",
  CLOSE_LIMIT_MODAL: "CLOSE_LIMIT_MODAL",

  GET_TABLE_DATA_REQUEST: "GET_TABLE_DATA_REQUEST",
  GET_TABLE_DATA_REQUEST_SUCCESS: "GET_TABLE_DATA_REQUEST_SUCCESS",
  GET_TABLE_DATA_REQUEST_ERROR: "GET_TABLE_DATA_REQUEST_ERROR",

  GET_MESSAGES_REQUEST: "GET_MESSAGES_REQUEST",
  GET_MESSAGES_REQUEST_SUCCESS: "GET_MESSAGES_REQUEST_SUCCESS",
  GET_MESSAGES_REQUEST_ERROR: "GET_MESSAGES_REQUEST_ERROR",
};
